FROM python:3.8

RUN mkdir -p /app/src

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

WORKDIR /app/src
COPY ./src .

EXPOSE 8000

ENV PYTHONPATH=/app/src
CMD python users/main.py
